import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useAuthContext } from "../contexts/AuthContext"
import HeaderComp from './components/Header'
import Footer from './components/Footer'
import homeImg from "./TourImg/homeImg.jpg"
import { Button } from '@chakra-ui/react'
const inter = Inter({ subsets: ['latin'] })
export default function Home() {
  const {user}= useAuthContext()
  return (
    <>
      <Head>
        <title>{user.name}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderComp/>
      <main className={styles.main}>
        <div style={{position:"relative"}}>
          <section style={{width:"35rem",height:"14rem",position:"absolute",top:"12rem",fontSize:"2.75rem",
          backgroundImage: "linear-gradient( to bottom right, rgba(125, 213, 111, 0.85), rgba(40, 180, 135, 0.85) )"
          ,borderRadius:"12px",opacity:"0.6",boxShadow: "rgba(50, 50, 93, 0.25) 0px 30px 60px -12px inset, rgba(0, 0, 0, 0.3) 0px 18px 36px -18px inset"
        }} >
          <span className='center-center' style={{fontWeight:"1000",margin:"10px",lineHeight:'1',wordWrap:"break-word",width:"100%",
          height:"70%",}}>BECOME ONE WITH NATURE</span>
          <div className='center-center' ><Button style={{backgroundColor:"#40916C"}}><Link href="/MainPage">
                    Explore
                </Link></Button></div>

          </section>
          {/* <p>
            {user.position}
          </p> */}
          
        </div>

          
      </main>
      <Footer/>
    </>
  )
}
